### 생성
POST http://localhost:8080/todo
Content-Type: application/json

{
  "title": "자바 공부하기"
}


### Todo 단건 조회 성공
GET http://localhost:8080/todo/1

### Todo 단건 조회 실패 - 없는 id
GET http://localhost:8080/todo/999

### Todo 생성
POST http://localhost:8080/todo
Content-Type: application/json

{
  "title": "자바 테스트2"
}

### Todo 수정 - title만 변경
PATCH http://localhost:8080/todo/1
Content-Type: application/json

{
  "title": "Spring 공부하기"
}

### Todo 삭제
DELETE http://localhost:8080/todo/1

### Todo 생성 공백
POST http://localhost:8080/todo
Content-Type: application/json

{
  "title": "                               "
}